---
title: "A very biased view of my recent research"
description: |
  A very biased overview of my recent research output as written for an internal promotion application. As such take everything with a large pinch of salt and replace all the I statements with We statements. 
author:
  - name: Sam Abbott
    url: https://samabbott.co.uk
date: 2022-04-11
creative_commons: CC BY
cite: true
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
---

A very biased overview of my recent research output as written for an internal promotion application. The brief was to summarise your research direction, your research output, steps taken to become an independent researcher, and then highlight 5 pieces of research output along with your contribution. As such take everything you read here with a large pinch of salt and replace all the I statements with We statements. However, if any of this sounds like fun to you then I am looking for collaborators and funding (ideally with few to no hoops). 

Note that this made me very uncomfortable to write and largely sharing as its hard to find samples of this kind of self-promotion. If you have feedback on how I can improve my writing with this aim in mind then please let me know.

## Research overview

My main research interest lies in developing, evaluating, and applying methods for improving our understanding of infectious disease dynamics in real-time. I am committed to doing science in the open, and collaboratively, with the aim of producing useful and actionable output. Most of my recent work has been targeted towards the COVID-19 response but my underlying focus is pathogen agnostic sparse data settings.

My current main areas of work are developing and evaluating methods for nowcasting right truncated data, developing and evaluating methods to forecast and understand variant dynamics, reconstructing unobserved infections from a range of data sources (such as count data and prevalence measures), and developing methods for the estimation of the effective reproduction number, the growth rate, and generation interval distribution as well as use cases for these estimates and understanding their interactions. Longer term, I seek to widen these research interests to integrate other novel data sources and pathogen specific feature with a focus on providing the methodology and tools required to improve future epidemic and pandemic responses in both high and low resource settings. More generally, I aim to ensure these tools are of use for surveillance and research use and will continue my focus of building sustainable communities around my software tooling.

Since the beginning of the pandemic I have been actively involved in the methodology and application of methods to estimate the effective reproduction number. This includes leading a [project](https://epiforecasts.io/covid/), in collaboration with the Met office, to estimate effective reproduction numbers across multiple geographies that had upwards of 500k users over two years and produced estimates that were used by multiple public health bodies (WHO, ECDC, UKHSA, etc) and numerous other research groups^[Read some reflections on this project here: https://samabbott.co.uk/posts/2022-03-25-rt-reflections/]. I supported this project by developing methodology to more accurately estimate the effective reproduction number^[some methodology details here: https://doi.org/10.12688/wellcomeopenres.16006.2] and released open source tooling democratising access to this approach^[EpiNow2: https://epiforecasts.io/EpiNow2]. These methods continue to be commonly used by others and are often used as a baseline by those developing tools for surveillance^[For example in this nice paper by Hay et al: https://doi.org/10.1126/science.abh0635].

As previously noted, much of my work in the last two years has been reactive and I have contributed numerous real-time reports on variants of concern mainly focussing on their [transmission advantage](https://doi.org/10.1101/2021.11.30.21267056), [severity](https://github.com/epiforecasts/covid19.sgene.utla.rt/releases/tag/v1.0), and [generation time](https://doi.org/10.1101/2022.01.08.22268920). Some of these contributions are reflected in my publication record though a large part took the form of real-time rapid reports disseminated via twitter and offical channels (i.e SPI-M). During the recent emergance of the Omicron variant I supported researchers at SACEMA^[See their great work here: https://www.sacema.org/] with their work on that variant. I have continued this support and will be travelling to South Africa in May for two weeks to present a seminar on my more recent tooling and to provide support to researchers there who are extending my earlier work on case fatality ratios estimated from population-level data. 

My most recent project has been to improve nowcasting methodology (correction of right truncated counts). I have done this by developing a novel extension to previous nowcasting methodology^[See nowcast methodology details here: https://epiforecasts.io/epinowcast/articles/model.html], releasing this in as a flexbile framework (in a space where such a tool has not been previously available)^[Nowcast package details here: https://epiforecasts.io/epinowcast], and developing a simple case study to facilitate use by others^[Nowcast case study details here: https://epiforecasts.io/eval-germany-sp-nowcasting/]. This work has then been contributed to the Germany nowcasting hub^[Germany nowcasting hub: https://covid19nowcasthub.de/], an international collaboration of researchers, which aims to provide daily nowcasts of German COVID-19 hospital admissions (one of the key metrics used by German policy makers). As an extension of this work I have released detailed daily evaluations of my own and others methodologies which have been used by myself and others to improve the quality of our nowcasts. I am now in the process of developing further collaborations on this work via a monthly open meeting and an active slack channel. This includes researchers at  ETH Zurich and Stockholm University who I am currently supporting in order to allow them to add their innovations to my core framework. I am also co-supervising a masters student at the University of Warwick who is aiming to apply this tooling to COVID-19 data.

I have also project managed (as PI) a number of recent pieces of work including the development of `covidregionaldata` an R package^[covidregionaldata: https://epiforecasts.io/covidregionaldata/] for accessing regional COVID-19 data authored by Joe Palmer^[Check out Joe's personal site here: https://joseph-palmer.github.io/] (a PhD student from Royal Holloway) during his placement at LSHTM, and `scoringutils` an R package^[scoringutills: https://epiforecasts.io/scoringutils/] for scoring forecasts (with a corresponding article in preparation) authored by Nikos Bosse^[Check Nikos's blog out here: https://followtheargument.org/] (PhD student at the school) for whom I also serve on his advisory committee.  

I am a co-investigator on two recent grant applications which have yet to return decisions. I am currently applying for a Chan Zuckerberg Initiative grant as part of the Essential Open Source Software for Science call to expand my suite of open source software and the community activities around them. In the course of the next year I aim to explore other funding streams such as the Wellcome Early Career Research Fellowship in order to expand the methodology behind my recent pandemic response work.

Outside of my core academic work I routinely share my research, and summaries of others research on twitter (where I have over 2k+ followers).

## Highlighted research

1. [Estimating the time-varying reproduction number of SARS-CoV-2 using national and subnational case counts](https://doi.org/10.12688/wellcomeopenres.16006.2)

This work was widely used as a surveillance tool globally during the COVID-19 pandemic and also represents a substantial methodological advance in the field. It continues to be used as a baseline for assessing the robustness of other methods. I led the development of methodology and open-source software to estimate the time-varying effective reproduction number. I also led the development of the website front-end, data pipeline, and computational pipeline (in collaboration with the Met office) to provide estimates for over 1000 locations each day. The [website](https://epiforecasts.io/covid/) where these estimates are presented has had over 500k unique users. Short-term forecasts from this pipeline have been submitted to SAGE, and the CDC and ECDC forecasting hubs. This work gave me insight into developing methods for real-time usage and their deployment at scale.

2. [Estimated transmissibility and impact of SARS-CoV-2 lineage B. 1.1. 7 in England](https://doi.org/10.1126/science.abg3055)

This work was conducted by a larger collaboration under intense time pressure over Christmas 2021. It impacted UK policy directly and was used globally to inform government responses. The approach taken in this study was to triangulate key values using multiple methods. I was responsible for the development of one of these analyses as well as reviewing the implementation of the other approaches used. This work built on the reproduction number estimate pipeline I led the development of and we extended and repurposed this approach to [estimate the transmissibility of the Delta variant](https://doi.org/10.1101/2021.11.30.21267056) and I subsequently further developed it to more robustly handle uncertainty^[Via a very clever (if I do say so myself) use of brms: https://github.com/epiforecasts/covid19.sgene.utla.rt/blob/main/R/variant_rt.r].

3. [Estimation of the test-to-test distribution as a proxy for generation interval distribution for the Omicron variant in England](https://doi.org/10.1101/2022.01.08.22268920)

This work provided real-time evidence that the generation interval for the Omicron variant may be shorter than for the Delta variant. Evidence for this was key to policy decisions made during the Omicron wave and this evidence was some of the first available. I led the development of the novel semi-mechanistic method that linked Omicron growth rates with non-Omicron growth rates. I also led the development of the underlying software package^[forecast.vocs: https://epiforecasts.io/forecast.vocs/] used to produce these growth rate estimates and an earlier real time report tracking the time-varying transmission advantage of Omicron in England^[See this real-time report, and the code supporting it here: https://epiforecasts.io/omicron-sgtf-forecast/]. 

 4. Evaluating Semi-Parametric Nowcasts of COVID-19 Hospital Admissions in Germany^[Real-time evaluation of nowcasting in Germany: https://epiforecasts.io/eval-germany-sp-nowcasting/, Nowcasting package: https://epiforecasts.io/epinowcast/]

Despite this work still being in progress I feel it captures the range of my research impact as it includes a core methodological development, work to democratise access to this development and previous developments, extensive and detailed evaluation (being drafted for peer review), offers utility to decision makers via the Germany nowcasting hub, support for other contributors for example researchers at ETH Zurich and at Stockholm University, and support for users for example the masters student at the University of Warwick who I will be co-supervising to use this tooling. By design it is modular and I expect this to be a fruitful area of research in the medium term. This project was undertaken fully independently with all aspects being planned and conducted without support from others.

5. [Feasibility of controlling COVID-19 outbreaks by isolation of cases and contacts](https://doi.org/10.1016/S2214-109X(20)30074-7)

This study was led by Joel Hellewell^[Check out his blog here: 
https://jhellewell14.github.io/] and was conducted in early 2020 when little was known about COVID-19. It provided timely and rigourous evidence[^There is some debate about this: https://doi.org/10.1016/S2214-109X(20)30219-9] that contact tracing alone would likely to insufficient for elimination and was widely used to inform policy. I supported all aspects of this analysis and led on the computational components which were crucial for its widespread reuse by other research groups.
