---
title: "How should we build methods and tools to prepare for future pandemics?"
description: |
  There are several models that we could take to develop methods and tools in order to prepare for future pandemics. We should talk about them.
author:
  - name: Sam Abbott
    url: https://samabbott.co.uk
date: 2022-10-13
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Pandemic preparedness has been in vogue for a while (for obvious reasons)^[There is a lot to this but here I just focus in on my domain interest which is processing data to get useful signals to inform decisions]. The majority of the conversation I've seen has been on how to get more, and longer term, funding and on specific initiatives we should focus on^[For example certain groups are very in faviour of metagenomic scanning and others want to develop a weather forecasting service for infectious disease.]. I have seen much less discussion about how we go about doing this work, whether our traditional research models are a good fit, or if something more is needed. When this is discussed the impression I get is that if traditional research is not the way to go then top down new organisations that have provider/user model are favoured but to me this seems like a potentially very risky way to go about things^[Borne out I think by the recent shuttering of the pandemic preparedness institute: https://www.science.org/content/article/cycles-panic-and-neglect-head-pandemic-prevention-institute-explains-its-early-death].

Over the last several years I have been working on real-time infectious disease modelling^[A very biased round-up for a (sadly unsuccessful) promotion application: https://samabbott.co.uk/posts/2022-04-11-a-very-biased-view-of-my-recent-research/] with the aim of providing evidence faster, and better, than was previously possible. In the main this has proved very very hard, as I know many others have found. In many cases the major issue has not been technical ability (though for me at least perhaps this is a limitation^[Some thoughts on limitations with my work here: https://samabbott.co.uk/posts/2022-09-19-80-percent-good-enough/]) or a lack of understanding of what the problem is but rather the sheer scope of the task and lack of resources linked with knowledge to even go about answering some of the more pressing questions in the amount of time available. This has been the case for both reactive work but also preparedness work where the timelines are longer (a few years) but the resourcs still seem insufficient.

For a while I have been convinced that a community approach^[See this starting to take shape here: https://www.epinowcast.org/] is the right way to go about this. What do I mean by this? I mean creating something where people (and ideally users) can contribute to a large project - or body of knowledgee - whilst retaining ownership, and the credit that comes with it, of their contributions. On the face of it this is how science already works but in practice I think contrasts with the traditional model where separate groups/organisations create competing tools and methodologies and then in theory (but often not in practive) provide these as a service to others^[Sound good? Get involved here: https://community.epinowcast.org]. This is a hard sell but quite a few practioners appear to agree. 

This could all just be my echo chamber and there are a wide range of views^[clearly given the numerous projects starting to take shape based on similar ideas but with very different approaches]. For a while I have been running Twitter polls^[I am a very serious scientist.] to scope out what people think. I recently came across [pol.is](https://pol.is/) which is a platform designed for these sort of conversations. From a first pass it seems great. Below is a conversation I've started aiming to find out what people think. Currently the questions are a pretty eclectic mix that I put together but you can and should submit your own. [Initial results](https://pol.is/report/r64ajcsmp9butzxhzj44c) are shaping up to be pretty interesting. 

If you find this useful or interesting please consider sharing it in your network. I think it's important we think more about how we do work before attention from this problem fades again.


<div class='polis' data-conversation_id='6ukkcvfbre'></div>
<script async src='https://pol.is/embed.js'></script>


