---
title: "My application to be an instructor with Applied Epi"
description: |
  The cover letter I provided as part of my application to be an instructor with the Applied Epi organisation. Contains background on the motivation for my work, details of my prior experience, and thoughts on user based software development.
author:
  - name: Sam Abbott
    url: https://samabbott.co.uk
date: 2022-08-19
creative_commons: CC BY
cite: true
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
---

Here I am sharing a public version of the cover letter I sent to [Applied Epi](https://appliedepi.org/) as part of my application to  be a course instructor. Applied Epi is a nonprofit that grew out of the community led development of the [Epidemiologist R handbook](https://appliedepi.org/epirhandbook/). This resource provides crowd sourced reference material for practioners working in applied epidemiology and public health. The applied epidemiology handbook is in my view one of the best developments to come out of the response to the COVID-19 pandemic. Unlike traditional resources, tools, and training it takes a bottom up community focussed approach that delivers what is needed and not what stakeholders think is needed. Since the development of the handbook they have expanded to provide training and community developed tools based on user need. Both of these are sorely needed so this is an exciting development. You could say that I am a fan.

I was very pleased to see tooling I developed as part of our COVID-19 response [featured](https://www.epirhandbook.com/en/epidemic-modeling.html) and found the comparison between other options informative for shaping my plans for future work. The key takeaway being that there is a large trade-off between optimal estimates and run-time. Users have different levels of technical expertise and computing resources and we need to build tools that provide gold standard estimates but that can also provide estimates of lower quality, with this quality reduction being quanitifable, when less time or resources are available. This was actually already a design focus of `EpiNow2` (as much as anything written after several months of working 7 days a week for 18 hours a day can be said to be designed) but poor documentation coverage and potentially less than optimal design decisions led to this being hard for users to discover.

Another reason to make this application public is that I am currently exploring future career options that enable me to develop tools and methods for real-time infectious disease analysis with a community driven approach. Please let me know if you are part of an organisation that can support this or know of opportunities. I'll be following up shortly with a 5 year research agenda that may provide useful additional detail. 


## Motivation

My motivation to join the Applied Epi team stems from the focus of my research work which aims to improve the real-time analysis of infectious disease in both outbreak and routine surveillance settings. I developed one of the leading packages^[EpiNow2: http://epiforecasts.io/EpiNow2] for real-time reproduction number estimation which is widely used by public health agencies and research groups responding to novel outbreaks and I am currently developing new tools and methods^[Focussed on the `epinowcast` package: https://epiforecasts.io/epinowcast]. A core part of this work is to understand the needs of users as without being of practical use my work has little point^[More detail on my recent research is available in the following reflective pieces: https://samabbott.co.uk/posts/2022-04-11-a-very-biased-view-of-my-recent-research/,  and https://epiforecasts.io/posts/2022-03-25-rt-reflections/index.html].

Currently to understand the needs of users I meet with practitioners from global health agencies and support them with their questions related to my areas of expertise. An example of this is case study which was developed with Sebatian Funk based on recent questions related to Monkeypox surveillance^[Nowcasting case study: https://github.com/epiforecasts/nowcasting.example/blob/main/inst/reports/epinowcast.md]. I also support research groups in person, for example SACEMA in South Africa^[See some of SACEMA's great work here: https://www.sacema.org/], when they need expertise at short notice. I would like to augment this by being involved with teaching practitioners in the early stages of their `R` journeys and ideally those learning about statistical modelling methodologies similar to those I develop. Aside from this selfish motivation, I am also a passionate advocate for open, democratised, science and see the work of Applied Epi as a great example of this. 

## Technical experience

I have worked as a data scientist managing data extraction (`SQL`, `R`), data management, developing analyses using the tidyverse, and delivering routine reports in Rmarkdown and as shiny dashboards based on models I built. I also developed a series of Shiny apps and packages for accessing Tuberculosis data^[`getTBinR`: https://github.com/seabbs/getTBinR], and democratising infectious disease models^[`idmodelr`: https://github.com/seabbs/idmodelr]. I am able to code in a range of styles with a preference for `data.table` in my own package development but believe it is key to adapt to a given project and user (as seen in my work). In recent years, I have shifted focus to more technical modelling work but have produced a series of real-time reports used as part of the UK government response to the COVID-19 pandemic and world-wide^[Some example real-time reports are: https://github.com/epiforecasts/covid19.sgene.utla.rt, and https://github.com/epiforecasts/omicron-sgtf-forecast]. I have also developed pipelines using the `targets` package and GitHub actions that are now in use by others for nowcasting^[Nowcasting `targets` pipeline: https://github.com/epiforecasts/eval-germany-sp-nowcasting] and forecasting^[Forecasting GitHub Actions pipeline: https://github.com/epiforecasts/simplified-forecaster-evaluation]. My technical weaknesses are in a lack of recent `SQL` experience, in geospatial mapping, and as I have no experience with data collection tools. 

## Professional experience

My background is in academic research but I have been heavily involved in the UK response to the COVID-19 pandemic supplying real-time reports to government advisory bodies (SPI-M and SAGE) as well as forecasts to the CDC and ECDC forecasting hubs and nowcasts to the Germany nowcasting hub. I teach on the LSHTM modern methods in infectious disease modelling course and lead the software engineering session. I also taught on the Bristol University introduction to infectious disease modelling course and was responsible for developing the open source course content^[BIDD infectious disease modelling course: https://bristolmathmodellers.github.io/biddmodellingcourse/]. I co-supervise one PhD student and have managed (as PI) two software development projects by students^[`covidregionaldata`: https://github.com/epiforecasts/covidregionaldata, `scoringutils`: https://github.com/epiforecasts/scoringutils] which involved large mentoring components. I am currently supervising a Masters student using `epinowcast` to explore the impact of reporting structures for COVID-19 surveillance data on nowcast performance in the UK. I run the LSHTM CMMID software engineering slack channel and have a reputation for providing support as asked both for LSHTM students and those who contact me via Twitter^[For example today: https://twitter.com/rafalpx/status/1560596503235665920]. My weaknesses in this area are that I have not worked for an applied epidemiology organisation and that in general my volume of teaching experience is somewhat limited.

## Code example

As previously noted, my code example^[Nowcasting case study: https://github.com/epiforecasts/nowcasting.example/blob/main/inst/reports/epinowcast.md] was developed as a case study in response to questions related to Monkeypox surveillance. It showcases the use of the [`epinowcast`](https://epiforecasts.io/epinowcast) package for symptom onset data that is reported with some delay, and some level of missingness, and where the analysis aim is to determine the underlying growth rate of the outbreak in real-time. The same repository also hosts a similar case study, largely written by Sebastian Funk, for the [`EpiNow2`](https://epiforecasts.io/epinowcast) package.  The `epinowcast` case study also serves as a development road map as all the challenges with data of these kind that are noted will be supported as features in the near-term. This kind of user driven development style is one that I would like to make more use of as we move away from the response period of the pandemic and as I myself do less real-time response driven work and more methodological development. This aim is also behind the community driven leadership structure we have adopted for `epinowcast` with monthly meetings of developers, users, and methodology experts to decide the future of the package.
