name: Build and Deploy Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

# Prevent concurrent deployments to avoid conflicts
concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  render-site:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        
      - name: Render site
        run: |
          Rscript build_site.R

      - name: Upload website artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          retention-days: 5
          path: _site

  publish-site:
    if: github.ref == 'refs/heads/main' && github.repository == 'seabbs/seabbs.github.io'
    needs: render-site
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create clean gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          
      - name: Download website artifact
        uses: actions/download-artifact@v4
        with:
          name: website
          path: .
          
      - name: Commit and push website
        run: |
          touch .nojekyll
          git add --all
          git commit -m "Deploy website to GitHub Pages"
          git push -f origin gh-pages
          echo "Website successfully published to GitHub Pages"
