on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

name: render-site

jobs:
  render-site:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-dependencies@v2
      - name: Render site
        run: |
          Rscript build_site.R

      - uses: actions/upload-artifact@v2
        with:
          name: website
          retention-days: 5
          path: _site

  publish-site:
    if: github.ref == 'refs/heads/main' && github.repository == 'seabbs/seabbs.github.io'
    needs: render-site
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Make a clean gh-pages branch
      run: |
        git checkout --orphan gh-pages
    - uses: actions/download-artifact@v2
      with:
        name: website
        path: .
    - name: Commit and push website
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action - Published website"
        git add --all
        git commit -m "Publish website"
        git push -f origin gh-pages:gh-pages
        echo "website published to GitHub"
